# Generated by Django 2.2.4 on 2019-08-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='id',
        ),
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=120, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=120, primary_key=True, serialize=False),
        ),
    ]
